"use strict";
exports.__esModule = true;
var gameState_1 = require("./gameState");
var sd = gameState_1["default"].nuevoJuego(8);
var asd = new gameState_1["default"](sd.tableroGS, 1);
//console.log(asd.getLegalMoves(1));
console.log('Inicio de juego...');
console.log(asd.tableroGS);
asd.jugadaRealizada([4, 2]);
console.log('Turno 1: Blanco');
console.log(asd.tableroGS);
asd.jugadaRealizada([5, 2]);
console.log('Turno 2: Negro');
console.log(asd.tableroGS);
